START TRANSACTION;

CREATE TABLE WAREHOUSES (
	WAREHOUSE_ID INT AUTO_INCREMENT PRIMARY KEY,
	CITY VARCHAR(100) NOT NULL,
	UNIQUE(CITY)
);

CREATE TABLE INVENTORY (
	WAREHOUSE_ID INT,
	SKU VARCHAR(50),
	STOCK_QUANTITY INT,
	PRIMARY KEY (WAREHOUSE_ID, SKU)
);

INSERT INTO WAREHOUSES (CITY)
VALUES 
	('STOCKHOLM'),
	('GÖTEBORG'),
	('MALMÖ');

COMMIT;
